name: Test Creatoria Core

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # позволяет запускать вручную

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установить зависимости
        run: |
          pip install numpy pyyaml

      - name: Запустить тест
        run: |
          python test_core.py